language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  api_key:
    secure: ShfQ34c9oGpL3mzCsah4Vm53FwtNrEdFfIuB2e7fdsCfzZnJTq+yYw8daiaxe/+uMu9xe1byBamgOy4SrjoHU52/hOwIRsvDIeCg61+ZczuUI5usSHclRmQlB+Vwu5SJMtbUq0wveHZG8+2Gf3J1v54DNmaNVjtMMyPWUUJxX65nny5834wavSfga7griVRbgZQMz7l60y2MJzs9F7Edras5vyWKPg9HQ9Rr1kfxUegR1/fjhNdjaaLStMtOWFIKx0h222DaNI1rrGHWqeMlhlocoJYZEtBYZjkkyYGn4fCcggo47Ki8pImpcA8xjC8TZezTND/PBE8Yt6eJsuiM5m4VQ3QZ2esJIPWFm463l6Jhy3hI7eHOYL9vyyZ/xo8iEItjhjM9dDTP94eFV2cqcg7p3FuqgX3rLLzTKMQZahSMAx9PTnJNoHvZOszix45Q+8Gx5tAAgQ8JRbAofvhlK3ywvR+GsFCe2dIbmpnecr94zWymF06CtG6qCu/RnxZ/1GeaOl+OxAGVP5Tqpm8cycwWz0c4HpAa+xNwj77JzBN5psYUKAopC5895//aPsOw1Em6vIsPs6hToWuv2aIGW/4E6sTpyuDKoxK1rMpMnnRsoewbGcdR0OyjML7GTmTJF/5YzZLSbjSWiSrx+L504rRcIgOLFiAI1JhZ2Q6oodk=
  on:
    tags: true
    repo: chinjs/chin-plugin-imagemin
    branch: publish
