language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  api_key:
    secure: cjXsm0F/FsM0X/iMryWzqPOVmkt1qHH47BevCJPxASYtPCzC0RO1b+nynnbdefdOzJJbS+qjGAZdqtXrlfJoj1jd/CAXgHqQGlFaB4HeRAYPB9mN6nz0FRT8Tmu2zxtub42ZpIO1lWl+sYnIvQE3xXMTwWKWoTltI6zUPJ4f+/kK6iiHDy1KvO2FqGw/Xp0SYoEjCQTeUaY7FmQl80/65M4ANq5fhJdXIXGTbLQJt8FEceHx6JiOvXGQ7ZomAT1OsmNtU3qJjFGzjJyEWBM1mFLedox58niYUDc6HBDHMYkNEaOsP9P636gT4ZmVMEfVdhKPEAsyxgWqtYynKh5tNJu02yj5KcGx13KyrVbdXZWefFcyrqATEr/2yvN3BcvBXex4NzzLiqcPF8pRrBlP39hcKgCmItIRyNt45P6a/0VFRpaXgu4tDlZVP91Hcwzm0uH10sZZAtaDp9OCeTRQyjg/TRnUTs01WgGdDiKSChDOpOUlHpfVicR7YkIHTW+nm6dWSY+OdlUP4WPFE0YUlPZtaGU6jXUSp24lDpZVRRd99m08P+SIk66Gw2I8Fm9Bhtu6QALP3dSXOhwQyM7wbglw55NgdCPIccaD3cR5gSvUsV0OIsOt8X95JVaFjlxvakQrxdil76ZSa22gwstG6KXkI9VjMZ5peVwkcCZbNh4=
  on:
    tags: true
    repo: chinjs/chin-plugin-imagemin
    branch: publish
